# Generated by Django 3.2.6 on 2022-01-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_demo',
            field=models.FileField(null=True, upload_to='videos_demo/', verbose_name=''),
        ),
    ]
