# Generated by Django 4.0 on 2022-03-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_order_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
